/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SignupRouteImport } from './app/signup'
import { Route as LoginRouteImport } from './app/login'
import { Route as HelloRouteImport } from './app/hello'
import { Route as CustomerRouteImport } from './app/customer'
import { Route as AdminSignupRouteImport } from './app/admin-signup'
import { Route as AdminRouteImport } from './app/admin'
import { Route as DashboardRouteRouteImport } from './app/dashboard/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as GameIndexRouteImport } from './app/game.index'
import { Route as DashboardIndexRouteImport } from './app/dashboard/index'
import { Route as GameGuideRouteImport } from './app/game.guide'
import { Route as GamePlayRoomCodeRouteImport } from './app/game.play.$roomCode'
import { Route as GameLobbyRoomCodeRouteImport } from './app/game.lobby.$roomCode'
import { Route as GameJoinRoomCodeRouteImport } from './app/game.join.$roomCode'
import { Route as DemoStartServerFuncsRouteImport } from './app/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './app/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './app/demo/api.names'
import { Route as ApiAuthSplatRouteImport } from './app/api.auth.$'
import { Route as DemoStartSsrIndexRouteImport } from './app/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './app/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './app/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './app/demo/start.ssr.data-only'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin-signup',
  path: '/admin-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const GameGuideRoute = GameGuideRouteImport.update({
  id: '/game/guide',
  path: '/game/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayRoomCodeRoute = GamePlayRoomCodeRouteImport.update({
  id: '/game/play/$roomCode',
  path: '/game/play/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLobbyRoomCodeRoute = GameLobbyRoomCodeRouteImport.update({
  id: '/game/lobby/$roomCode',
  path: '/game/lobby/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GameJoinRoomCodeRoute = GameJoinRoomCodeRouteImport.update({
  id: '/game/join/$roomCode',
  path: '/game/join/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-signup': typeof AdminSignupRoute
  '/customer': typeof CustomerRoute
  '/hello': typeof HelloRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/game/guide': typeof GameGuideRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/game/': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/game/join/$roomCode': typeof GameJoinRoomCodeRoute
  '/game/lobby/$roomCode': typeof GameLobbyRoomCodeRoute
  '/game/play/$roomCode': typeof GamePlayRoomCodeRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-signup': typeof AdminSignupRoute
  '/customer': typeof CustomerRoute
  '/hello': typeof HelloRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/game/guide': typeof GameGuideRoute
  '/dashboard': typeof DashboardIndexRoute
  '/game': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/game/join/$roomCode': typeof GameJoinRoomCodeRoute
  '/game/lobby/$roomCode': typeof GameLobbyRoomCodeRoute
  '/game/play/$roomCode': typeof GamePlayRoomCodeRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-signup': typeof AdminSignupRoute
  '/customer': typeof CustomerRoute
  '/hello': typeof HelloRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/game/guide': typeof GameGuideRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/game/': typeof GameIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/game/join/$roomCode': typeof GameJoinRoomCodeRoute
  '/game/lobby/$roomCode': typeof GameLobbyRoomCodeRoute
  '/game/play/$roomCode': typeof GamePlayRoomCodeRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/admin'
    | '/admin-signup'
    | '/customer'
    | '/hello'
    | '/login'
    | '/signup'
    | '/game/guide'
    | '/dashboard/'
    | '/game/'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/game/join/$roomCode'
    | '/game/lobby/$roomCode'
    | '/game/play/$roomCode'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-signup'
    | '/customer'
    | '/hello'
    | '/login'
    | '/signup'
    | '/game/guide'
    | '/dashboard'
    | '/game'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/game/join/$roomCode'
    | '/game/lobby/$roomCode'
    | '/game/play/$roomCode'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/admin'
    | '/admin-signup'
    | '/customer'
    | '/hello'
    | '/login'
    | '/signup'
    | '/game/guide'
    | '/dashboard/'
    | '/game/'
    | '/api/auth/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/game/join/$roomCode'
    | '/game/lobby/$roomCode'
    | '/game/play/$roomCode'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminSignupRoute: typeof AdminSignupRoute
  CustomerRoute: typeof CustomerRoute
  HelloRoute: typeof HelloRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  GameGuideRoute: typeof GameGuideRoute
  GameIndexRoute: typeof GameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  GameJoinRoomCodeRoute: typeof GameJoinRoomCodeRoute
  GameLobbyRoomCodeRoute: typeof GameLobbyRoomCodeRoute
  GamePlayRoomCodeRoute: typeof GamePlayRoomCodeRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-signup': {
      id: '/admin-signup'
      path: '/admin-signup'
      fullPath: '/admin-signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/game/guide': {
      id: '/game/guide'
      path: '/game/guide'
      fullPath: '/game/guide'
      preLoaderRoute: typeof GameGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/play/$roomCode': {
      id: '/game/play/$roomCode'
      path: '/game/play/$roomCode'
      fullPath: '/game/play/$roomCode'
      preLoaderRoute: typeof GamePlayRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/lobby/$roomCode': {
      id: '/game/lobby/$roomCode'
      path: '/game/lobby/$roomCode'
      fullPath: '/game/lobby/$roomCode'
      preLoaderRoute: typeof GameLobbyRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/join/$roomCode': {
      id: '/game/join/$roomCode'
      path: '/game/join/$roomCode'
      fullPath: '/game/join/$roomCode'
      preLoaderRoute: typeof GameJoinRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminSignupRoute: AdminSignupRoute,
  CustomerRoute: CustomerRoute,
  HelloRoute: HelloRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  GameGuideRoute: GameGuideRoute,
  GameIndexRoute: GameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  GameJoinRoomCodeRoute: GameJoinRoomCodeRoute,
  GameLobbyRoomCodeRoute: GameLobbyRoomCodeRoute,
  GamePlayRoomCodeRoute: GamePlayRoomCodeRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
